### ISSUE TITLE
EU Cookie banner does not close

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/eu-cookie-law-widget#3]
The owner of the site `https://therevitalizedchickpea.com/` reported in 1171646-zen that their cookie widget does not close. I was able to replicate this on my test site and found that no matter which theme I use it does not close and seems to be reloading the page upon click the close button. I tested on BroadSheet, Small Business, and Dyad2.

I didn't find any console errors when clicking on the close button.

Tested on: Chrome, Firefox, and Safari on the latest versions.

**Comment by Piyopiyo-Kitsune** [comment]
This bug seems to be caused by having more than one EU cookie widget active in any of your widget areas.  I recommend only allowing one instance of this widget to be enabled.

**Comment by designsimply** [comment]
Thank you for reporting this issue!

I have moved the issue to 8066-wpcom because this repository appears to be outdated (last change was made on Sep 15, 2016) and separate from the WordPress.com version of the widget.
