### ISSUE TITLE
Closed widget flickers on new page load after closing

### ISSUE THREAD

**Issue by jesscga** [Automattic/eu-cookie-law-widget#6]
## Summary
After accepting cookie widget, the widget closes, but then flashes for a split second when going to another page on the site.

## Steps to Reproduce

1. Go to https://alleretretour.com
2. Accept Cookie Law widget
3. Navigate to another page or refresh current page

### Expected Result
Cookie widget should not appear

### Actual Result
Cookie widget blinks while page is loading and then vanishes

Screencast: http://cld.wthms.co/efpbac

I watched the source code rendering while the page loads and don't see any HTML or CSS evidence of the cookie widget.

I was unable to reproduce on a test site.

I tried deactivating `siteorigin-panels` and `wp-user-avatar` plugins and there was no change. The only other active plugins are a8c plugins (Jetpack, Akismet, and AMP)

## Site info

- Site URL: https://alleretretour.com
- Plan: WordPress.com Business plan
- Ticket ID / Forum thread ID / Chat ID: 1511087-zen

**Comment by sdixon194** [comment]
Bumping, user has been frequently requesting an update.  Did you try changing themes @jesscga ?

**Comment by jesscga** [comment]
Good idea, @sdixon194 :) Just sent an email asking them to try switching themes or let us know when we can test that.

**Comment by jesscga** [comment]
User's theme is Lenscap. @gpmw tried changing theme to Twenty Seventeen and Storefront and the flicker went away. 

I activated Lenscap on a test site and wasn't able to recreate the flicker. I'll test more with the theme + the site's plugins to see if I can figure out what's triggering it.

Replied to user letting them know that theme is part of the issue.

**Comment by jesscga** [comment]
I set up a set site with the following criteria to mimic the site in question:

Business plan
Lenscap theme
Jetpack
Akismet
AMP
Page Builder by Site Origin
WP User Avatar

I can't recreate the flickering cookie box so I'm reluctant to call it a theme bug

**Comment by jesscga** [comment]
I tried moving the widget from the Sidebar to the Footer and it seems to have stopped the flickering. Waiting for user to confirm that it's the same on their end.

**Comment by jesscga** [comment]
Worked for user! Closing issue :)
